// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID          int32            `json:"id"`
	OrderID     int32            `json:"order_id"`
	Status      string           `json:"status"`
	Amount      pgtype.Numeric   `json:"amount"`
	PaymentMode string           `json:"payment_mode"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
