// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID           int32            `json:"id"`
	AggregateKey string           `json:"aggregate_key"`
	EventType    string           `json:"event_type"`
	Payload      []byte           `json:"payload"`
	Published    bool             `json:"published"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Payment struct {
	ID          int32            `json:"id"`
	OrderID     int32            `json:"order_id"`
	Status      string           `json:"status"`
	Amount      pgtype.Numeric   `json:"amount"`
	PaymentMode string           `json:"payment_mode"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
