// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments(
    order_id,
    status,
    amount,
    payment_mode
)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, status, amount, payment_mode, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID     int32          `json:"order_id"`
	Status      string         `json:"status"`
	Amount      pgtype.Numeric `json:"amount"`
	PaymentMode string         `json:"payment_mode"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Status,
		arg.Amount,
		arg.PaymentMode,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, status, amount, payment_mode, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int32) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentsByOrderID = `-- name: GetPaymentsByOrderID :many
SELECT id, order_id, status, amount, payment_mode, created_at, updated_at FROM payments WHERE order_id = $1
`

func (q *Queries) GetPaymentsByOrderID(ctx context.Context, orderID int32) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Status,
			&i.Amount,
			&i.PaymentMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2
WHERE id = $1
RETURNING id, order_id, status, amount, payment_mode, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.PaymentMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
