// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (order_id, message)
VALUES ($1, $2) RETURNING id, order_id, message, created_at, updated_at
`

type CreateNotificationParams struct {
	OrderID int32  `json:"order_id"`
	Message string `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.OrderID, arg.Message)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationsByOrderId = `-- name: GetNotificationsByOrderId :many
SELECT id, order_id, message, created_at, updated_at FROM notifications WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByOrderId(ctx context.Context, orderID int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
