// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	GetNotificationsByOrderId(ctx context.Context, orderID int32) ([]Notification, error)
}

var _ Querier = (*Queries)(nil)
