// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package store

import (
	"context"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (
    product_id,
    available_quantity
)
VALUES ($1, $2)
RETURNING product_id, available_quantity, created_at, updated_at
`

type CreateInventoryParams struct {
	ProductID         int32 `json:"product_id"`
	AvailableQuantity int32 `json:"available_quantity"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.AvailableQuantity)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementInventory = `-- name: DecrementInventory :execrows
UPDATE inventory
SET available_quantity = available_quantity - $2
WHERE product_id = $1
AND available_quantity >= $2
`

type DecrementInventoryParams struct {
	ProductID         int32 `json:"product_id"`
	AvailableQuantity int32 `json:"available_quantity"`
}

func (q *Queries) DecrementInventory(ctx context.Context, arg DecrementInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementInventory, arg.ProductID, arg.AvailableQuantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInventoryByProductId = `-- name: GetInventoryByProductId :one
SELECT product_id, available_quantity, created_at, updated_at 
FROM inventory
WHERE product_id = $1
`

func (q *Queries) GetInventoryByProductId(ctx context.Context, productID int32) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProductId, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.AvailableQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInventory = `-- name: IncrementInventory :exec
UPDATE inventory
SET available_quantity = available_quantity + $2
WHERE product_id = $1
`

type IncrementInventoryParams struct {
	ProductID         int32 `json:"product_id"`
	AvailableQuantity int32 `json:"available_quantity"`
}

func (q *Queries) IncrementInventory(ctx context.Context, arg IncrementInventoryParams) error {
	_, err := q.db.Exec(ctx, incrementInventory, arg.ProductID, arg.AvailableQuantity)
	return err
}
