// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package store

import (
	"context"
)

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_key, event_type, payload, published, created_at FROM outbox WHERE published = FALSE ORDER BY created_at ASC
`

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateKey,
			&i.EventType,
			&i.Payload,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox (aggregate_key, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, aggregate_key, event_type, payload, published, created_at
`

type InsertOutboxEventParams struct {
	AggregateKey string `json:"aggregate_key"`
	EventType    string `json:"event_type"`
	Payload      []byte `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent, arg.AggregateKey, arg.EventType, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.AggregateKey,
		&i.EventType,
		&i.Payload,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox SET published = TRUE WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
