// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	DecrementInventory(ctx context.Context, arg DecrementInventoryParams) (int64, error)
	GetInventoryByProductId(ctx context.Context, productID int32) (Inventory, error)
	IncrementInventory(ctx context.Context, arg IncrementInventoryParams) error
}

var _ Querier = (*Queries)(nil)
