// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int32            `json:"id"`
	CustomerID  int32            `json:"customer_id"`
	Status      string           `json:"status"`
	TotalAmount pgtype.Numeric   `json:"total_amount"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type OrderItem struct {
	ID        int32            `json:"id"`
	OrderID   int32            `json:"order_id"`
	ProductID int32            `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	UnitPrice pgtype.Numeric   `json:"unit_price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
