// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetOrderItemsByOrderId(ctx context.Context, orderID int32) ([]OrderItem, error)
	ListOrdersByCustomer(ctx context.Context, customerID int32) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
